services:
    node:
        image: node:22.13-alpine
        container_name: frontend
        working_dir: /var/www/html
        restart: unless-stopped
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - .:/var/www/html
        command: ["/bin/sh", "-c", "npm run dev"]
        networks:
            - frontend_network

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        networks:
            - monitoring_network
        ports:
            - "9090:9090"
        volumes:
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus-data:/prometheus
        restart: unless-stopped

    node-exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node-exporter
        networks:
            - monitoring_network
        volumes:
            - "/:/host:ro,rslave"
        command: --path.rootfs=/host
        restart: unless-stopped

    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        networks:
            - monitoring_network
            - frontend_network
        ports:
            - "3000:3000"
        restart: unless-stopped
        environment:
            - GF_SECURITY_ALLOW_EMBEDDING=true
        volumes:
            - grafana-data:/var/lib/grafana

networks:
    frontend_network:
        name: frontend_network
        driver: bridge
    monitoring_network:
        name: monitoring_network
        driver: bridge

volumes:
    prometheus-data:
        name: prometheus-data
        driver: local
    grafana-data:
        name: grafana-data
        driver: local
