services:
    node:
        image: node:22-alpine
        container_name: frontend
        working_dir: /var/www/html
        restart: unless-stopped
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - .:/var/www/html
        command: ["/bin/sh", "-c", "npm install --force && npm run dev"]
        networks:
            - frontend_network

networks:
    frontend_network:
        name: frontend_network
        driver: bridge
