services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "${APP_PORT:-8080}:80"
            - "${APP_SSL_PORT:-443}:443"
        volumes:
            - "./:/var/www/html"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
            - "./nginx/certbot/conf:/etc/letsencrypt"
            - "./nginx/certbot/www:/var/www/certbot"
        networks:
            - backend_network
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        depends_on:
            - php-fpm

    certbot:
        image: certbot/certbot:latest
        container_name: certbot
        volumes:
            - "./nginx/certbot/conf:/etc/letsencrypt"
            - "./nginx/certbot/www:/var/www/certbot"
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    php-fpm:
        container_name: backend
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - "./:/var/www/html"
            - "./docker/php/conf.d/php.ini:/usr/local/etc/php/php.ini"
            - "./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
            - "./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini"
        environment:
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-127.0.0.1}
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        ports:
            - 9001:9001
            - 9003:9003
        networks:
            - backend_network
        depends_on:
            - mysql
            - redis
            # - rabbitmq

    mysql:
        container_name: mysql
        image: "mysql/mysql-server:8.0"
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "mysql-volume:/var/lib/mysql"
            - "./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
        networks:
            - backend_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: "${DB_PORT:-3306}"
        ports:
            - "${PHPMYADMIN_PORT:-8081}:80"
        networks:
            - backend_network
        depends_on:
            - mysql

    redis:
        container_name: redis
        image: "redis:alpine"
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - "redis_volume:/data"
        restart: unless-stopped
        networks:
            - backend_network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    redisinsight:
        container_name: redisinsight
        image: redislabs/redisinsight:latest
        ports:
            - "${REDISINSIGHT_PORT:-5540}:5540"
        networks:
            - backend_network
        depends_on:
            - redis

    meilisearch:
        container_name: meilisearch
        image: getmeili/meilisearch:latest
        restart: unless-stopped
        ports:
            - "${MEILISEARCH_PORT:-7700}:7700"
        networks:
            - backend_network
        volumes:
            - "meilisearch_volume:/meili_data"

    # rabbitmq:
    #     container_name: rabbitmq
    #     image: rabbitmq:3-management
    #     hostname: rabbitmq
    #     restart: always
    #     ports:
    #         - "${RABBITMQ_PORT:-5672}:5672"
    #         - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    #     networks:
    #         - backend_network
    #     volumes:
    #         - "rabbitmq_volume:/var/lib/rabbitmq"
    #     environment:
    #         - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-rabbitmq}
    #         - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-rabbitmq}
    #         - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    #     healthcheck:
    #         test:
    #             - CMD
    #             - rabbitmqctl
    #             - status
    #         retries: 3
    #         timeout: 5s

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "${MAILHOG_PORT:-8025}:8025"
        networks:
            - backend_network

    supervisor:
        container_name: supervisor
        build:
            context: ./docker/supervisor
            dockerfile: Dockerfile
        volumes:
            - "./:/var/www/html"
            - "./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf"
        restart: unless-stopped
        networks:
            - backend_network

    matomo:
        container_name: matomo
        image: matomo
        restart: unless-stopped
        volumes:
            - "matomo_volume:/var/www/html:z"
        environment:
            - MATOMO_DATABASE_HOST=mysql
        ports:
            - "${MATOMO_PORT:-8082}:80"
        networks:
            - backend_network

networks:
    backend_network:
        name: backend_network
        driver: bridge

volumes:
    mysql-volume:
        driver: local
        name: mysql-volume
    redis_volume:
        driver: local
        name: redis_volume
    meilisearch_volume:
        driver: local
        name: meilisearch_volume
    rabbitmq_volume:
        driver: local
        name: rabbitmq_volume
    matomo_volume:
        driver: local
        name: matomo_volume
