services:
    matomo:
        image: matomo
        container_name: matomo
        restart: unless-stopped
        volumes:
            - matomo_data:/var/www/html:z
        environment:
            MATOMO_DATABASE_HOST: matomo_db
            MATOMO_DATABASE_DBNAME: matomo
            MATOMO_DATABASE_USERNAME: matomo
            MATOMO_DATABASE_PASSWORD: SecurePass123
            MATOMO_DATABASE_ADAPTER: mysql
        ports:
            - ${MATOMO_PORT:-8082}:80
        networks:
            - frontend_network
        depends_on:
            - matomo_db

    matomo_db:
        image: mysql
        container_name: matomo_db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: RootPass123
            MYSQL_DATABASE: matomo
            MYSQL_USER: matomo
            MYSQL_PASSWORD: SecurePass123
        volumes:
            - matomo_db_data:/var/lib/mysql
        networks:
            - frontend_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-u${MYSQL_USER}"
                - "-p${MYSQL_PASSWORD}"
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    matomo_data:
        name: matomo_data
        driver: local
    matomo_db_data:
        name: matomo_db_data
        driver: local

networks:
    frontend_network:
        external: true
