<template>
    <div>
        <section id="team">
            <page-title
                title="Meet our team"
                subtitle="Meet the team of professionals to serve you"
            />

            <team-basic :team-members="teamMembers" />
        </section>

        <section id="clients" class="my-12 text-center">
            <page-title
                title="What our happy client say"
                subtitle="Veniam proident aute magna anim excepteur et ex consectetur velit ullamco veniam minim aute sit. Elit occaecat officia et laboris Lorem minim. Officia do aliqua adipisicing ullamco in"
            />

            <clients-basic :reviews="reviews" />
        </section>

        <section
            id="metrics"
            class="min-h-[250px] flex flex-col items-center justify-center"
        >
            <page-title title="Application Metrics" />

            <metrics-basic :stats="stats" />
        </section>

        <section id="integrations" class="my-10">
            <page-title
                title="Integrations"
                subtitle="Integrations refer to the process of combining different software systems or components to work together seamlessly. This involves connecting various applications."
            />

            <integrations-basic :integrations="integrations" />
        </section>
    </div>
</template>

<script lang="ts" setup>
const teamMembers = [
    {
        id: 1,
        name: 'John Doe',
        role: 'CEO',
        image: 'https://readymadeui.com/team-1.webp',
        facebook: 'https://www.facebook.com/johndoe',
        twitter: 'https://twitter.com/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
    },
];

const reviews = [
    {
        id: 1,
        user: {
            name: 'John Doe',
            image: 'https://readymadeui.com/team-2.webp',
        },
        rating: 3,
        text: 'The service was amazing. I never had to wait that long for my food. The staff was friendly and attentive, and the delivery was impressively prompt.',
    },
];

const stats = [
    {
        value: 5.4,
        suffix: 'M+',
        label: 'Total Users',
        description: 'The total number of registered users on the platform.',
    },
    {
        value: 80,
        suffix: 'K',
        label: 'Revenue',
        description: 'The total revenue generated by the application.',
    },
    {
        value: 100,
        suffix: 'K',
        label: 'Engagement',
        description:
            "The level of user engagement with the application's content and features.",
    },
    {
        value: 99.9,
        suffix: '%',
        label: 'Server Uptime',
        description:
            'The percentage of time the server has been operational and available.',
    },
];

const integrations = [
    {
        link: 'https://stripe.com',
        description:
            'Stripe is a payment processing platform that allows businesses to accept payments online.',
        icon: 'logos:stripe',
    },
    {
        link: 'https://google.com/analytics',
        description:
            'Google Analytics is a web analytics service that provides insights into website traffic and user behavior.',
        icon: 'logos:google-analytics',
    },
    {
        link: 'https://mailchimp.com',
        description:
            'Mailchimp is a marketing platform that allows businesses to send emails to their audience.',
        icon: 'logos:mailchimp-freddie',
    },
    {
        link: 'https://slack.com',
        description:
            'Slack is a communication platform that allows teams to collaborate and communicate effectively.',
        icon: 'logos:slack',
    },
];
</script>
