name: Code Analysis

on: [push, pull_request]

jobs:
    eslint:
        name: Eslint
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - name: Install Dependencies
              working-directory: frontend
              run: npm install
            - name: Run Eslint
              working-directory: frontend
              run: npm run lint

    larastan:
        name: LaraStan
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  coverage: none
            - name: Install Composer Dependencies
              working-directory: backend
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Run Static Analysis
              working-directory: backend
              run: composer phpstan
