name: Eslint

on:
    push:
        branches: ["main", "development"]
    pull_request:
        branches: ["main", "development"]

jobs:
    eslint:
        name: Eslint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [20, 22, 23]
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: "npm"
            - name: Run Eslint
              working-directory: frontend
              run: npm run lint
