name: Release
on:
    release:
        types: [published]

jobs:
    update-version:
        name: Update version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
            - name: Update version file
              run: |
                  echo '{"version": "${{ github.ref_name }}", "build_date": "$(date +%Y-%m-%d)"}' > version.json
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "Update version to ${{ github.ref_name }}"
                  branch: "main"
